slick.dbs.default.profile="slick.jdbc.PostgresProfile$"
   slick.dbs.default.db.driver="org.postgresql.Driver"
   slick.dbs.default.db.url="jdbc:postgresql://localhost:5432/biddit_db"
   slick.dbs.default.db.user="postgres"
   slick.dbs.default.db.password="123456789"
   play.evolutions.enabled=true

    filters.disabled += "play.filters.csrf.CSRFFilter" # Explicitly disable CSRF
jwt.secret = "ehehhe"